export const dateFormats = {
 DATE_FORMAT_0 : 'DD Month YYYY',
 DATE_FORMAT_1 : 'DD/MM/YYYY',
 DATE_FORMAT_2 : 'MM/DD/YYYY',
 DATE_FORMAT_3 : 'DD/MM/YYYY HH:mm',
 DATE_FORMAT_4 : 'MM/DD/YYYY HH:mm',
 DATE_FORMAT_5 : 'MM/DD/YYYY h:mm:ss A',
 DATE_FORMAT_6 : 'DD/MM/YYYY h:mm:ss A',
 DATE_FORMAT_7 : 'DD Month YYYY h:mm:ss A',
 DATE_FORMAT_8 : 'DD-MM-YYYY',
 DATE_FORMAT_9 : 'MM-DD-YYYY',
}