export const fileTypes = {
    VIDEO_EXTENSION : 'mp4',
    AUDIO_EXTENSION : 'mp3',
    MIME_VIDEO: 'video/mp4',
    MIME_AUDIO_1: 'audio/mp3',
    MIME_AUDIO_2 : 'audio/mpeg',
    MIME_EXCEL_1 : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    MIME_EXCEL_2 : 'application/vnd.ms-excel',
    IMAGE_EXTENSION_1: 'jpg',
    IMAGE_EXTENSION_2: 'jpeg',
    IMAGE_EXTENSION_3: 'png',
    MIME_IMAGE_1: 'image/jpg',
    MIME_IMAGE_2: 'image/jpeg',
    MIME_IMAGE_3: 'image/png',
    PDF_EXTENSION: 'pdf',
    MIME_PDF_1: 'application/pdf',
    POWERPOINT_EXTENSION: 'ppt',
    MIME_POWERPOINT_1: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    MIME_POWERPOINT_2: 'application/vnd.ms-powerpoint.presentation.12',
    MIME_POWERPOINT_3: 'application/vnd.ms-powerpoint',
   }